<?xml version="1.0" encoding="utf-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <layoutAssignments>
        <layout>Case-Temp</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Temp</layout>
        <recordType>Case.Default</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Temp</layout>
        <recordType>Case.Tecon_Rio_Grande</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CaseClose-Temp</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CaseClose-Temp</layout>
        <recordType>Case.Default</recordType>
    </layoutAssignments>
    <recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Case.Default</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.Tecon_Rio_Grande</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
</Profile>